# Batch Processor - Non-Critical Component
# This deployment demonstrates the lowest availability class
# Suitable for batch jobs, dev/test workloads
apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-processor
  namespace: components
  labels:
    app: batch-processor
    oda.tmforum.org/componentName: batch-processor
    oda.tmforum.org/componentType: management
  annotations:
    oda.tmforum.org/availability-class: "non-critical"
    oda.tmforum.org/component-function: "management"
    oda.tmforum.org/componentName: "batch-processor"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: batch-processor
  template:
    metadata:
      labels:
        app: batch-processor
        oda.tmforum.org/componentName: batch-processor
    spec:
      containers:
        - name: processor
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: batch-processor
  namespace: components
  labels:
    app: batch-processor
spec:
  selector:
    app: batch-processor
  ports:
    - port: 80
      targetPort: 80
      name: http
