---
# Customer Management Component - High Availability (critical for business)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management-api
  namespace: demo-critical
  labels:
    app: customer-management
    oda.tmforum.org/component: customer-management
    component-function: core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: customer-management
  template:
    metadata:
      labels:
        app: customer-management
        oda.tmforum.org/component: customer-management
    spec:
      containers:
        - name: api
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: customer-management-api
  namespace: demo-critical
  labels:
    app: customer-management
spec:
  selector:
    app: customer-management
  ports:
    - port: 80
      targetPort: 80
